### PR TITLE
Add pseudo element tests

### PR DESCRIPTION
**Pull request by gtrufitt**
Mainly just for me to get my head around it a little, but also to test `::` works (it does 👍). Though maybe we'll lint that out?

Does this make sense? Feel free to close the PR if not...

### CODE REVIEW

**Comment by gtrufitt** [comment]
To be fair, I could have just added the `::` variety to the existing pseudo test, shall I do that instead @sndrs?

**Comment by sndrs** [comment]
does this duplicate the current pseudo test?

**Comment by sndrs** [comment]
ah no - nice one. but maybe it could be added to it?

**Comment by gtrufitt** [comment]
Yeah, I'll just add the double `::` to the existing pseudo!

**Comment by sndrs** [comment]
yeah go for it. wonder if chained pseudos work? i think they *should*

**Comment by gtrufitt** [comment]
Is this what you meant by chaining pseudos?

Also, adding this check into the pseudo test (basically same rules, one with double `::` so should just output the one `.class:after` and one class mapping in the json:

```
.pseudo:after {
    content: 'pseudo:after';
}

.pseudo::after {
    content: 'pseudo:after';
}
```

Errors out with this:

```
Object{pseudo:["a","b","f"],"pseudo-3":["b"],"no-pseudo":["c"],"pseudo-2":["d"],"no-pseudo-2":["e"]}

Object{pseudo:["a","b","f","f"],"pseudo-3":["b"],"no-pseudo":["c"],"pseudo-2":["d"],"no-pseudo-2":["e"]}
```

Like it doesn't filter out existing? I would like to work out why that is, but maybe you know immediately :)

**Comment by sndrs** [comment]
ah sorry, no – as in `.pseudo--chained:selected:hover`

**Comment by sndrs** [comment]
i added your test example to the current pseudo one. i had to update the main task to accommodate doubles, so nice one :)

**Pull request closed without merging**
