### PR TITLE
Expand more shorthand properties

### PR DESCRIPTION
**Pull request by sndrs**

### CODE REVIEW

**Comment by sndrs** [comment]
@desbo your huge class test reveals something quite interesting here. wonder what the best thing to do is? not expand borders?

**Comment by desbo** [comment]
I guess almost all uses will want the full border property, so it's probably safe to not expand it and just add the specific classes for any longhand border properties that exist. 

On the other hand the only cost of expanding it would be adding 3 extra classes to any elements that use the shorthand, which I guess would marginally increase the page size, but I don't really see that being that useful, so yeah I'd say don't expand them.

**Comment by sndrs** [comment]
i think it could be good to expand shorthand values, but not properties? this is a live example from the graun:

```css
.1Isi7t { border-top: 0.0625rem solid #b3b3b4; }
.1LIRaW { border-top: 0.0625rem solid #bdbdbd; }
.1NCBGh { border-top: 0.0625rem solid #cc2b12; }
.1PzoAM { border-top: 0.0625rem solid #da8c80; }
.1PNjCW { border-top: 0.0625rem solid #dcdcdc; }
.1Q0wYk { border-top: 0.0625rem solid #dfdfdf; }
.1ORh1G { border-top: 0.0625rem solid #e6e1c3; }
.1RJqGg { border-top: 0.0625rem solid #eaeaea; }
.1RRzAb { border-top: 0.0625rem solid #ececec; }
.1Qx7A0 { border-top: 0.0625rem solid #f0f0f0; }
.1QBc2s { border-top: 0.0625rem solid #f1f1f1; }
```
turning this into
```css
.a { border-top-width: 0.0625rem }
.b { border-top-style: solid }
.c { border-top-color: #b3b3b4 }
.d { border-top-color: #bdbdbd }
.e { border-top-color: #cc2b12 }
.f { border-top-color: #da8c80; }
.g { border-top-color: #dcdcdc; }
.h { border-top-color: #dfdfdf; }
.i { border-top-color: #e6e1c3; }
.j { border-top-color: #eaeaea; }
.k { border-top-color: #ececec; }
.l { border-top-color: #f0f0f0; }
.m { border-top-color: #f1f1f1; }
```
seems ok?

**Comment by sndrs** [comment]
then again,

```css
.a { border-top: 0.0625rem solid #b3b3b4; }
.b { border-top: 0.0625rem solid #bdbdbd; }
.c { border-top: 0.0625rem solid #cc2b12; }
.d { border-top: 0.0625rem solid #da8c80; }
.e { border-top: 0.0625rem solid #dcdcdc; }
.f { border-top: 0.0625rem solid #dfdfdf; }
.g { border-top: 0.0625rem solid #e6e1c3; }
.h { border-top: 0.0625rem solid #eaeaea; }
.i { border-top: 0.0625rem solid #ececec; }
.j { border-top: 0.0625rem solid #f0f0f0; }
.k { border-top: 0.0625rem solid #f1f1f1; }
```
compresses smaller...

**Comment by sndrs** [comment]
136b vs 159b. not much in it...

**Comment by sndrs** [comment]
but also fewer rules to parse. hmmm....

**Comment by desbo** [comment]
to me the second one seems better, mainly going by what you said and it needing fewer classes on each element

**Comment by sndrs** [comment]
don't think this is a good idea for now. maybe it could do multiple passes to work out the best way to break a given set of CSS down, but will worry about that later

**Pull request closed without merging**
